### ISSUE TITLE
SciPy 2022 informations – Friday Grand Ballroom, 2:35pm & sprint organisation

### ISSUE THREAD

**Issue by Carreau** [jupyter/papyri#166]
Talk is moved to Grand ballroom at 2:35.

Slides are [here](https://docs.google.com/presentation/d/1qnGbKt0Av_73Xu_qSE1tSeb-Zn-fHg69wg5UWL_ZWJM/edit?usp=sharing).

jupyterLab extension is [there](https://github.com/carreau/papyri-lab), 
having the question mark operator work currently requires [this branch](https://github.com/carreau/ipython/tree/papyri-hook-example) of IPython.

This issue will be updated with link to slides, and other informations like sprint etc...

**Comment by willingc** [comment]
Nicely done @Carreau 🎉
