### ISSUE TITLE
BUG: doesn't work in Windows 11 due to error in `there` package

### ISSUE THREAD

**Issue by sohang3112** [jupyter/papyri#176]
On Windows 11, running `papyri install numpy` fails with the error `ModuleNotFoundError: No module named 'syslog'`.

This is because of the following lines of code in `__init__.py` file in `there` package (which is used by `papyri`):
```python
if platform.platform() == "Windows":
    import syslog
```
This fails on Windows 11, because `platform.platform()` returns *Windows-10-10.0.22000-SP0* on Windows 11. 

I have opened [this PR](https://github.com/Carreau/there/compare/master...sohang3112:there:patch-1) to fix the issue in `there` package.

**Comment by Carreau** [comment]
Thanks, apologies, for the late reply – had some health issues two weeks ago and I've trying to catchup with tings. I've released a new version of `there` with your fixes. In the end `there` should not be a dependency, it is there just for debugging. 

Closing, let me know if you still have issues. I know that tree-sitter and the rst parser are not easy to install on windows either.

**Comment by sohang3112** [comment]
Ok. Hope you are in good health now 🙂

**Comment by Carreau** [comment]
> Hope you are in good health now

THanks, yes, much better. Slowly cathcing up on things !
