### ISSUE TITLE
Add a comment to PR after vercel preview deployment

### ISSUE THREAD

**Issue by aktech** [jupyter/papyri#213]
At the moment we have to go to the github actions run to find out the preview link, it would be nice to comment the preview in the PR itself

**Comment by Carreau** [comment]
Any thought of trying https://github.com/marketplace/actions/github-status-action to have a status instead of posting a comment ? That may produce less mails/notifications.
Haven't tried it though.

**Comment by aktech** [comment]
> Any thought of trying https://github.com/marketplace/actions/github-status-action to have a status instead of posting a comment ? That may produce less mails/notifications.

Yeah, definitely. We can use that, would be fairly straightforward to change.
