### ISSUE TITLE
Work better with --dry-run/don't write to disk.

### ISSUE THREAD

**Issue by Carreau** [jupyter/papyri#74]
Currently there is a `papyri gen` has a `--dry-run` (`gen.py:gen_main`) option that tries to not write to disk. 
It is a bit of an ad-hoc solution. 

We should figure out a more generic way to either:
 - Make it no-op, maybe via a MockUp pathlib, 
 - Or actually use MakeTempdir and use this as a target (and cleanup on exit)

I tend to prefer the second solution as this would also help us ensure that the paths  are not hardcoded.

**Comment by Carreau** [comment]
@steff456 that should be pretty straitforward, and you likely need to touch a single function, do you want to give it a shot ?

**Comment by steff456** [comment]
@Carreau I'll work on this!

**Comment by steff456** [comment]
I'm closing this issue because #75 was already merged
