### ISSUE TITLE
Update Graphstore to make proper use of SQLite.

### ISSUE THREAD

**Issue by Carreau** [jupyter/papyri#86]
My apologies, this is going to be a bit of a brain dump, is is not completely finalized in my head, my SQL vocabulary is also limited.

The goal of the graphstore is to keep tracks of references between "pages", though we want to keep in mind that a page may have multiple version, so many of the sql recipe you find online won't work. 

My thought are the following:
 
- A source document can be represented by a 4-tuple key: (package, version, category, identifier) 
- A destination document can be represented by a 3-tuple (package, category, identifier). No version as generally when say scipy reference numpy it does not link to a particular version...
- A link is a 2 tuple (source,destination), but let's make it a 3 tuple (source, destination, metadata).

I'd like to have a way to insert a document into the graphstore/sql, that make it easy to keep things coheremt, so I'm thinking

3 tables:
SOURCE, DEST, LINKS
- Source with source key primary id, and package, version, category, identifier
- Dest with dest key primary id package, category, identifier
- And Link with Foreign key to source, Foreign key to id and a 3rd metadata field.

Now I'm not super familiar with SQL but: is there a ways to go garbage collection on DEST ? That is to say that if nothing in the Link table refers to it it's culled ? 

And what would the API to insert objects into it look like ? Do I have to do three operations on Source/Dest/Link when inserting a list of references ? can I "insert if does not exists or otherwise  do nothing and return the primary id" ?

**Comment by steff456** [comment]
> Now I'm not super familiar with SQL but: is there a ways to go garbage collection on DEST ? That is to say that if nothing in the Link table refers to it it's culled ?

SQLite doesn't enable procedures or functions that modify the database, we can only create functions that add new registers but cannot modify/delete existing entries. So the answer is that we will need a script that runs periodically checking for non-existing links. The other alternative is to use another database management system that allows us to create procedures, I'm still navigating how things are working right now so I prefer not to mention any particular system yet.

> And what would the API to insert objects into it look like ? Do I have to do three operations on Source/Dest/Link when inserting a list of references ? 

That's easy, you just need to create a cursor in Python and create a layer that is able to communicate to the db. The idea of this cursor is to just write normal SQL queries such as `INSERT XYZ ...`. And yes, you will need to do one operation per table and they have to be in order. So if the link table has two foreign keys, then you will need to first insert in the source and dest tables before adding a new entry to the link table.

> can I "insert if does not exists or otherwise do nothing and return the primary id" ?

Given that is a relational db, you will have an error when trying to insert things that are not following the structure of the tables. However, you can handle that error as needed. 

Hope this helps! The structure of the database that you are currently thinking seems fine to me as well :)

**Comment by Carreau** [comment]
> So the answer is that we will need a script that runs periodically checking for non-existing links.

Well we can make this part of the Python API. 

> The other alternative is to use another database management system that allows us to create procedures, I'm still navigating how things are working right now so I prefer not to mention any particular system yet.

That is a no-no, we can't have a server, it has to be something that is Python installable and does not run in the background.

Yes, I know you would get an error, I was wondering if you can use a varaiation of UPSERT, or if you need to do a query and an insert after.

**Comment by steff456** [comment]
> Well we can make this part of the Python API.

That sounds like a good plan! 

> Yes, I know you would get an error, I was wondering if you can use a varaiation of UPSERT, or if you need to do a query and an insert after.

Indeed, you need to do a query and insert after

**Comment by steff456** [comment]
While I was working on actually writing the schema I realized we can make this with just two tables,

1. `documents` that stores the information of each package as `key primary id, and package, version, category, identifier`
2. `links` that stores `source, dest, metadata` 

In this way the garbage collection from dest just by removing a link rather than having an other table and having to update all the others. I'm going to investigate if there's a way to have a cascade drop, in which if a package is removed from the `documents` table then all the entries that point to it in the `links` table will be removed.

**Comment by steff456** [comment]
I'm closing this issue because it is fixed in #98

**Comment by Carreau** [comment]
> I realized we can make this with just two tables

That was my original thought, but you can have two kind of link:
 - to a particular version
 - to any version. 

Also, we might have a link to a document that does not exist (yet). 

So imagine that (scipy, module, 1.8, scipy.special) want to link to "any" numpy array, you would get a (numpy, module, *, numpy.array) in destination, which is not a particular document.

Of course it is not implemented so you couldn't have guessed, or maybe there is another way to do it with only two tables I don't see ? 

Questions for cascade, I guess the deletion happens when the last foreign key is removed, is that right ?
