### ISSUE TITLE
Configuration option for global example setup

### ISSUE THREAD

**Issue by rossbar** [jupyter/papyri#90]
I was interested in trying `papyri` out on some projects, so I copied an example `toml` file and tried running on `networkx`.

The running of nearly all the examples fails with `NameError: name 'nx' is not defined` because the NX sphinx documentation uses the `doctest_global_setup` option to run `import networkx as nx` for every doctest example.

Is there a similar configuration option for `papyri` yet when running the examples?

**Comment by Carreau** [comment]
See #92, and https://github.com/networkx/networkx/pull/5381, 

I'll for now avoid having a global setup that is executable (I'm trying to stay as declarative as possible).

Mostly I want to refine the config system so you can have easier config per submodule/objects. 

I'm thinking:

```
[networkx]

... config

[networkx.foo]
.. extra config that apply to all `nx.foo` and subobject.

[networkx.foo.bar]
....
```

I also want a config flag that tell us if current object should be available in docstrings, and should siblings from current module be as well.
