### ISSUE TITLE
Configuration Expected Errors.

### ISSUE THREAD

**Issue by Carreau** [jupyter/papyri#93]
Right now there are many places that just keep going on errors like here:

https://github.com/jupyter/papyri/blob/de177552a3cec7e6d1fc5702af5598a9f43e8165/papyri/gen.py#L1669-L1680 and configuration that skip problematic examples:

https://github.com/jupyter/papyri/blob/de177552a3cec7e6d1fc5702af5598a9f43e8165/examples/scipy.toml#L5-L210

It would be good to have something like the following in configuration:

```
[expected_errors]
VisitSubstitutionDefinitionNotImplementedError = ['networkx.algorithms.approximation.vertex_cover', networkx.algorithms.approximation.something_else]
```

And verify that the errors we get is the one we expect.

Part of that has been done in #94.

Currently the `early_error` can only be done in config file.
We should 

  - [ ] add a `--fail-early/--no-fail-early` CLI flag that overwrite the option.
  - [ ] Add a flag to fail if the are expected errors that have not been encountered.

**Comment by Carreau** [comment]
@steff456 is that something you want to look at while I'm looking at #89 ?

**Comment by steff456** [comment]
Sure! I will look into this :)
